### ISSUE TITLE
你好，我碰到一个问题

### ISSUE THREAD

**Issue by wuboy19** [zhangwm-pt/prebuilt_whl#1]
licheepi 4a python3.11 
这个是错误信息
cv2.error: OpenCV(4.5.4) /mnt/git/github/opencv-python/opencv/modules/highgui/src/window.cpp:1257: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvNamedWindow'

**Comment by wuboy19** [comment]
我知道了是虚拟环境不能调用那个

**Comment by wuboy19** [comment]
我发现是好像是缺少函数的问题

**Comment by zhangwm-pt** [comment]
> 我发现是好像是缺少函数的问题

嗯，是的，这是因为我编译 opencv 的环境中没有 gtk2.0，所以，编译完成的 opencv 不支持图形界面相关的功能

**Comment by zhangwm-pt** [comment]
#5 更新了一个带 gtk2.0 的 opencv whl
