### ISSUE TITLE
你好大佬我可以在问一个问题吗

### ISSUE THREAD

**Issue by dragonforward** [zhangwm-pt/prebuilt_whl#2]
首先，大佬感谢你的回复
我就是按照文档把自己的yolox模型部署，测试成功了，所以想要通过摄像头实时输入达到效果，图像化的效果，然后我想询问一下我是安装大佬你的whl，是不是我可以用通过下载opencv源码然后再licheepi 4a上进行编译安装的话，是不是可以达到我想要的效果，然后或者是哪里有这方面的生成riscv64架构的对应whl文件，十分感谢大佬

**Comment by zhangwm-pt** [comment]
嗯，可以通过下载opencv 源码然后在 licheepi4a 上编译，至少原理上是可行的……
我目前是通过 riscv64 QEMU+docker 来编译生成 whl 的，这是我的编译环境 https://www.yuque.com/za4k4z/uzn618/duo06v2tvrd2ceuf ，也可以参考一下。

**Comment by dragonforward** [comment]
谢谢大佬，我去尝试，十分感谢

**Comment by zhangwm-pt** [comment]
这是一个源码编译 torchvision 的示例，https://github.com/zhangwm-pt/prebuilt_whl/wiki/Build-torchvision-from-source
