### ISSUE TITLE
大佬，提一个问题

### ISSUE THREAD

**Issue by wuboy19** [zhangwm-pt/prebuilt_whl#3]
我现在在安装文档安装，如果是要4a使用是不是我得编译环境python3.11，现在环境是python3.8.10，然后cmake选项是不是安装网上那个就可以

**Comment by zhangwm-pt** [comment]
是的，如果你是在其他环境里面帮 licheepi 4a 编译 whl 安装包。那么需要跟licheepi 4a 上面的python版本一致。cmake 选项通常不需要修改，但也要视实际情况而定。

**Comment by wuboy19** [comment]
好的谢谢大佬
